{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1d1347bf-78be-49ab-98f7-7f3988f17a53",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yash: Hello my Fellow ISRO Scientist!\n",
      "yash: I'm an ISRO scientist, my name is yash raj but people call me yash\n",
      "yash: I'll be assisting you with your rocket mission\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "yash: now, what could be your name? yash\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yash: hello there yash !\n",
      "yash: enter the number of the planet or moon you desire to send a rover/probe to!\n",
      "1.Moon 2.Mercury 3.Venus 4.Mars 5.Jupiter 6.Saturn 7.Uranus 8.Neptune\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      " 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yash: Moon huh, that's a great choice! \n",
      "  In hindi moon is referred as chaand\n",
      "yash: Fun Fact :- The Moon stabilizes Earth's tilt, helping maintain a relatively stable climate over long periods.\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "yash: name your rocket lyma\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "yash: That's a great name for a rocket!\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter a date (DD/MM/YYYY):  09/04/2026\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Weather report\n",
      "yash: the weather is good \n",
      "##### LAUNCH DAY #####\n",
      "yash: It's Finally launch day today! it's the result of efforts of ISRO scientists\n",
      "yash:today we are going to launch lyma !\n",
      "yash: It's finally time to launch.\n",
      "Announcement: lyma launches today i.e. 09/04/2026\n",
      "lyma launches in......\n",
      "10\n",
      "9\n",
      "8, Whole country's watching the countdown with you\n",
      "7\n",
      "6\n",
      "5, hearts of 1 billion people hope for this mission's success\n",
      "4\n",
      "3\n",
      "2, but still, you stay calm and wait for your rocket to launch\n",
      "1\n",
      "\u0007 BOOM \u0007\n",
      "lyma FINALLY LAUNCHES SUCCESSFULLY!!\n",
      "yash: now that doesn't mean we have succeceded our mission\n",
      "yash: afterall success rate is only 42%, that is only 3 out of 7 chances\n",
      " few days later.....\n",
      "yash: oh no! there's CME(Coronal Mass Ejection,It's when a massive burst of solar wind and magnetic fields rising above the solar corona or being released into space.)\n",
      "yash: our spacecraft elctronics have been disturbed\n",
      "yash: unfortunately it's a failure\n",
      "yash: you have to try again later\n",
      "never give up until then because that's what an ISRO scientist does\n"
     ]
    }
   ],
   "source": [
    "#Indian Space Research Organization Rocket mission simulator\n",
    "#by future ISRO scientist THAKUR YASHRAJ SINGH\n",
    "import time as tm\n",
    "import random as rn\n",
    "from datetime import datetime\n",
    "from dateutil.relativedelta import relativedelta\n",
    "def type_effect(text):\n",
    "    for ch in text:\n",
    "        print(ch, end=\"\", flush=True)\n",
    "        tm.sleep(0.05)   # speed control\n",
    "    print()\n",
    "type_effect(\"yash: Hello my Fellow ISRO Scientist!\")\n",
    "type_effect(\"yash: I'm an ISRO scientist, my name is yash raj but people call me yash\")\n",
    "type_effect(\"yash: I'll be assisting you with your rocket mission\")\n",
    "name=input(\"yash: now, what could be your name?\")\n",
    "tm.sleep(2)\n",
    "print(\"yash: hello there\",name,\"!\")\n",
    "type_effect(\"yash: enter the number of the planet or moon you desire to send a rover/probe to!\")\n",
    "print(\"1.Moon\",\"2.Mercury\",\"3.Venus\",\"4.Mars\",\"5.Jupiter\",\"6.Saturn\",\"7.Uranus\",\"8.Neptune\")\n",
    "\n",
    "def destination_selection():\n",
    "    planet=int(input())\n",
    "    if planet==1:   #moon\n",
    "        print(\"yash: Moon huh, that's a great choice!\",\"\\n\",\" In hindi moon is referred as chaand\")\n",
    "        tm.sleep(2)\n",
    "        print(\"yash: Fun Fact :- The Moon stabilizes Earth's tilt, helping maintain a relatively stable climate over long periods.\")\n",
    "    elif planet==2:    #Mercury\n",
    "        print(\"yash: Mercury huh, that's a great chioce!\",\"\\n\",\" In hindi Mercury is referred as Budh grah\")\n",
    "        tm.sleep(2)\n",
    "        print(\"yash: Fun Fact :- A year on Mercury lasts only 88 Earth days. It races around the Sun faster than any other planet.\")\n",
    "    elif planet==3:    #Venus\n",
    "        print(\"yash: Venus huh, that's a great chioce!\",\"\\n\",\" In hindi Venus is referred as Shukra grah\")\n",
    "        tm.sleep(2)\n",
    "        print(\"yash: Fun Fact :-Venus rotates so slowly that a single day on Venus is longer than its entire year.\")       \n",
    "    elif planet==4:    #Mars\n",
    "        print(\"yash: Mars huh, that's a great choice!\",\"\\n\",\" In hindi Mars is referred as Mangal grah\")\n",
    "        tm.sleep(2)\n",
    "        print(\"yash: Fun Fact :- Mars experiences seasons just like Earth because its axis is tilted.\")        \n",
    "    elif planet==5:    #Jupiter\n",
    "        print(\"yash: Jupiter huh, that's a great choice!\",\"\\n\",\" In hindi Jupiter is referred as Brihaspati grah\")\n",
    "        tm.sleep(2)\n",
    "        print(\"yash: Fun Fact :- Jupiter acts like a giant cosmic shield, its gravity capturing or deflecting many objects that might otherwise head toward the inner Solar System.\")\n",
    "        tm.sleep(2)\n",
    "    elif planet==6:    #Saturn\n",
    "        print(\"yash: Saturn huh, that's a great choice!\",\"\\n\",\" In hindi Saturn is referred as Shani grah\")\n",
    "        print(\"yash: Fun Fact :- Saturn's rings are incredibly thin compared to their width; if Saturn were the size of a house, many parts of the rings would be thinner than a sheet of paper in proportion.\")\n",
    "        tm.sleep(2)\n",
    "    elif planet==7:    #Uranus\n",
    "        print(\"yash: Uranus huh, that's a great choice!\",\"\\n\",\" In hindi Uranus is referred as Arun grah\")\n",
    "        tm.sleep(2)\n",
    "        print(\"yash: Fun Fact :- Uranus rotates on its side, making its seasons among the most extreme in the Solar System.\")        \n",
    "    elif planet==8:    #Neptune\n",
    "        print(\"yash: Neptune huh, that's a great choice!\",\"\\n\",\" In hindi Neptune is referred as Varun grah\")\n",
    "        tm.sleep(2)\n",
    "        print(\"yash: Fun Fact :- Even though Neptune is the farthest major planet from the Sun, it has some of the fastest winds ever observed on a planet.\")        \n",
    "    else:\n",
    "        print(\"yash: Invalid choice!\")\n",
    "        return destination_selection()\n",
    "    return planet\n",
    "destination_selection()   \n",
    "roc_name=input(\"yash: name your rocket\")\n",
    "print(\"yash: That's a great name for a rocket!\")\n",
    "def weather_report(date_str):\n",
    "    print(\"Weather report\")\n",
    "    weather=rn.randint(1,4)\n",
    "    if weather==1:\n",
    "        print(\"yash: the weather is good \")\n",
    "        final_date=date_str\n",
    "    elif weather==2:\n",
    "        print(\"yash: the weather doesn't look so good, but still we can launch\")\n",
    "        final_date=date_str\n",
    "    elif weather==3:\n",
    "        print(\"yash: perfect weather for launch\")\n",
    "        final_date=date_str\n",
    "    elif weather==4:\n",
    "        print(\"yash: the weather look very bad! we must delay our launch!\")\n",
    "        try:\n",
    "            date = datetime.strptime(date_str, \"%d/%m/%Y\")\n",
    "            n=rn.randint(3,7)\n",
    "            print(\"the weather look good after\",n,\"days\")\n",
    "            new_date = date + relativedelta(days=n)\n",
    "            print(\"New Date:\", new_date.strftime(\"%d/%m/%Y\"))\n",
    "            final_date=new_date.strftime(\"%d/%m/%Y\")\n",
    "        except ValueError:\n",
    "            print(\" Invalid date! Please enter a valid date in DD/MM/YYYY format.\")\n",
    "            date_str = input(\"Enter a date (DD/MM/YYYY): \")\n",
    "            final_date=date_str\n",
    "    return final_date            \n",
    "def launch_date(date_str):\n",
    "    try:\n",
    "        date = datetime.strptime(date_str, \"%d/%m/%Y\")\n",
    "    except ValueError:\n",
    "        print(\" Invalid date! Please enter a valid date in DD/MM/YYYY format.\")\n",
    "        date_str = input(\"Enter a date (DD/MM/YYYY): \")\n",
    "    final_date=weather_report(date_str)\n",
    "    return final_date\n",
    "####LAUNCH DAY####\n",
    "date_str = input(\"Enter a date (DD/MM/YYYY): \")\n",
    "final_date=launch_date(date_str)\n",
    "print(\"##### LAUNCH DAY #####\")\n",
    "tm.sleep(2)\n",
    "print(\"yash: It's Finally launch day today! it's the result of efforts of ISRO scientists\")\n",
    "tm.sleep(2)\n",
    "print(\"yash:today we are going to launch\",roc_name,\"!\")\n",
    "tm.sleep(2)\n",
    "print(\"yash: It's finally time to launch.\")\n",
    "tm.sleep(2)\n",
    "print(\"Announcement:\",roc_name,\"launches today i.e.\",final_date)\n",
    "tm.sleep(2)\n",
    "print(roc_name,\"launches in......\")\n",
    "tm.sleep(2)\n",
    "print(\"10\")\n",
    "tm.sleep(1)\n",
    "print(\"9\")\n",
    "tm.sleep(1)\n",
    "type_effect(\"8, Whole country's watching the countdown with you\")\n",
    "tm.sleep(1)\n",
    "print(\"7\")\n",
    "tm.sleep(1)\n",
    "print(\"6\")\n",
    "tm.sleep(1)\n",
    "type_effect(\"5, hearts of 1 billion people hope for this mission's success\")\n",
    "tm.sleep(1)\n",
    "print(\"4\")\n",
    "tm.sleep(1)\n",
    "print(\"3\")\n",
    "tm.sleep(1)\n",
    "type_effect(\"2, but still, you stay calm and wait for your rocket to launch\")\n",
    "tm.sleep(2)\n",
    "print(\"1\")\n",
    "tm.sleep(1)\n",
    "print(\"\\a BOOM \\a\")\n",
    "tm.sleep(0.5)\n",
    "print(roc_name,\"FINALLY LAUNCHES SUCCESSFULLY!!\")\n",
    "tm.sleep(1)\n",
    "print(\"yash: now that doesn't mean we have succeceded our mission\")\n",
    "tm.sleep(1)\n",
    "print(\"yash: afterall success rate is only 42%, that is only 3 out of 7 chances\")\n",
    "tm.sleep(5)\n",
    "####End of launch day####\n",
    "type_effect(\" few days later.....\")\n",
    "space_activity=rn.randint(1,7)\n",
    "if space_activity==1: #solar flare\n",
    "    type_effect(\"yash: oh no! there's a solar flare(when powerful radiation bursts out of sun)\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: our communication systems and electronic are damaged\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: unfortunately it's a failure\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: you have to try again later\")\n",
    "    type_effect(\"never give up until then because that's what an ISRO scientist does\")\n",
    "elif space_activity==2: #Coronal Mass Ejection\n",
    "    type_effect(\"yash: oh no! there's CME(Coronal Mass Ejection,It's when a massive burst of solar wind and magnetic fields rising above the solar corona or being released into space.)\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: our spacecraft elctronics have been disturbed\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: unfortunately it's a failure\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: you have to try again later\")\n",
    "    type_effect(\"never give up until then because that's what an ISRO scientist does\")\n",
    "elif space_activity==3: #Micro meteoroid Impact\n",
    "    type_effect(\"yash: oh no! there's a Micrometeoroid Impact (when small space rocks with high speed collide with the spacecraft)\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: our solar panels have been destroyed!\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: unfortunately it's a failure\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: you have to try again later\")\n",
    "    type_effect(\"never give up until then because that's what an ISRO scientist does\")\n",
    "elif space_activity==4: #Space Debris Collision\n",
    "    type_effect(\"yash: oh no! there's a Space Debris Collision(when parts of old satellites collide with the spacecraft)\")\n",
    "    tm.sleep(1)\n",
    "    print(\"yash: our spacecraft has been destroyed\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: unfortunately it's a failure\")\n",
    "    tm.sleep(1)\n",
    "    type_effect(\"yash: you have to try again later\")\n",
    "    type_effect(\"never give up until then because that's what an ISRO scientist does\")\n",
    "else:\n",
    "    type_effect(\"yash: there's no abnormal activity\")\n",
    "    tm.sleep(1)\n",
    "    print(\"yash:\",roc_name,\"will continue to go on it's predicted trajectory!\")\n",
    "    ### mission successful ###\n",
    "    if planet==1: #moon\n",
    "        print(\"yash: finally\",roc_name,\"has successfully reached the moon! after travelling over 3,84,400 km for 40 days!\")\n",
    "        tm.sleep(1)\n",
    "        mission_date=datetime.strptime(final_date,\"%d/%m/%Y\")\n",
    "        print(\"yash: It's\",mission_date+relativedelta(days=40),\"today\")\n",
    "        type_effect(\"Few days later.....\")\n",
    "        tm.sleep(3)\n",
    "        print(\"yash: after a few days of observation, samples collected with the help of our rover, this is what we can conclude\")\n",
    "        print(\"===== MISSION REPORT =====\")\n",
    "        print(\"Evidence of water ice detected in permanently shadowed craters.\")\n",
    "        print(\"Local resources may support future human settlements.\")\n",
    "        print(\"Moon is suitable as a staging base for deep-space missions.\")\n",
    "        print(\"THIS MISSION IS HEREBY CONSIDERED A SUCCESS\")\n",
    "        print(\"CONGRATULATIONS!!\")\n",
    "        print(\"\\n\",\"\\n\",\"yash: CONGRATULATIONS\",name,\"YOU HAVE MADE INDIA PROUD!!\")        \n",
    "    elif planet==2: #mercury\n",
    "        print(\"yash: finally\",roc_name,\"has successfully reached mercury! after travelling over 77 million km for 7 months!\")\n",
    "        tm.sleep(1)\n",
    "        mission_date = datetime.strptime(final_date,\"%d/%m/%Y\")\n",
    "        print(\"yash: It's\",mission_date + relativedelta(months=7))\n",
    "        type_effect(\"Few days later.....\")\n",
    "        tm.sleep(3)\n",
    "        print(\"yash: after a few days of observation, samples collected with the help of our rover, this is what we can conclude\")\n",
    "        print(\"===== MISSION REPORT =====\")\n",
    "        print(\"Water ice deposits confirmed near the polar regions\")\n",
    "        print(\"Extreme temperatures make long-term human habitation difficult.\")\n",
    "        print(\"Robotic mining missions may be possible in the future.\")\n",
    "        print(\"THIS MISSION IS HEREBY CONSIDERED A SUCCESS\")\n",
    "        print(\"CONGRATULATIONS!!\")\n",
    "        print(\"\\n\",\"\\n\",\"yash: CONGRATULATIONS\",name,\"YOU HAVE MADE INDIA PROUD!!\")\n",
    "    elif planet==3: #venus\n",
    "        print(\"yash: finally\",roc_name,\"has successfully reached venus! after travelling over 41 million km for 5 months!\")\n",
    "        tm.sleep(1)\n",
    "        mission_date = datetime.strptime(final_date,\"%d/%m/%Y\")\n",
    "        print(\"yash: It's\",mission_date + relativedelta(months=5))\n",
    "        type_effect(\"Few days later.....\")\n",
    "        tm.sleep(3)\n",
    "        print(\"yash: after a few days of observation, samples collected with the help of our rover, this is what we can conclude\")\n",
    "        print(\"===== MISSION REPORT =====\")\n",
    "        print(\"Surface conditions remain hostile to human life.\")\n",
    "        print(\"Upper atmosphere may be suitable for future floating research stations.\")\n",
    "        print(\"No evidence of life was detected.\")\n",
    "        print(\"THIS MISSION IS HEREBY CONSIDERED A SUCCESS\")\n",
    "        print(\"CONGRATULATIONS!!\")\n",
    "        print(\"\\n\",\"\\n\",\"yash: CONGRATULATIONS\",name,\"YOU HAVE MADE INDIA PROUD!!\")\n",
    "    elif planet==4: #mars\n",
    "        print(\"yash: finally\",roc_name,\"has successfully reached mars! after travelling over 225 million km for 9 months!\")\n",
    "        tm.sleep(1)\n",
    "        mission_date = datetime.strptime(final_date,\"%d/%m/%Y\")\n",
    "        print(\"yash: It's\",mission_date + relativedelta(months=9))\n",
    "        type_effect(\"Few days later.....\")\n",
    "        tm.sleep(3)\n",
    "        print(\"yash: after a few days of observation, samples collected with the help of our rover, this is what we can conclude\")\n",
    "        print(\"===== MISSION REPORT =====\")\n",
    "        print(\"Large underground water reserves were discovered.\")\n",
    "        print(\"Mars is considered the most promising planet for future human colonies.\")\n",
    "        print(\"Organic compounds indicate Mars may once have supported microbial life.\")\n",
    "        print(\"THIS MISSION IS HEREBY CONSIDERED A SUCCESS\")\n",
    "        print(\"CONGRATULATIONS!!\")\n",
    "        print(\"\\n\",\"\\n\",\"yash: CONGRATULATIONS\",name,\"YOU HAVE MADE INDIA PROUD!!\")\n",
    "    elif planet==5: #jupiter\n",
    "        print(\"yash: finally\",roc_name,\"has successfully reached jupiter! after travelling over 588 million km for 6 years!\")\n",
    "        tm.sleep(1)\n",
    "        mission_date = datetime.strptime(final_date,\"%d/%m/%Y\")\n",
    "        print(\"yash: It's\",mission_date + relativedelta(years=6))\n",
    "        type_effect(\"Few days later.....\")\n",
    "        tm.sleep(3)\n",
    "        print(\"yash: after a few days of observation with the help of our probe, this is what we can conclude\")\n",
    "        print(\"===== MISSION REPORT =====\")\n",
    "        print(\"No solid surface suitable for settlement was found.\")\n",
    "        print(\"Several moons show signs of subsurface oceans.\")\n",
    "        print(\"Future exploration should focus on Jupiter's moons rather than the planet itself.\")\n",
    "        print(\"THIS MISSION IS HEREBY CONSIDERED A SUCCESS\")\n",
    "        print(\"CONGRATULATIONS!!\")\n",
    "        print(\"\\n\",\"\\n\",\"yash: CONGRATULATIONS\",name,\"YOU HAVE MADE INDIA PROUD!!\")\n",
    "    elif planet==6: #saturn\n",
    "        print(\"yash: finally\",roc_name,\"has successfully reached saturn! after travelling over 1.2 billion km for 8 years!\")\n",
    "        tm.sleep(1)\n",
    "        mission_date = datetime.strptime(final_date,\"%d/%m/%Y\")\n",
    "        print(\"yash: It's\",mission_date + relativedelta(years=8))\n",
    "        type_effect(\"Few days later.....\")\n",
    "        tm.sleep(3)\n",
    "        print(\"yash: after a few days of observation with the help of our probe, this is what we can conclude\")\n",
    "        print(\"===== MISSION REPORT =====\")\n",
    "        print(\"Saturn itself is unsuitable for human habitation.\")\n",
    "        print(\"Data suggests some moons contain ingredients necessary for life.\")\n",
    "        print(\"Future missions are recommended to explore these moons.\")\n",
    "        print(\"THIS MISSION IS HEREBY CONSIDERED A SUCCESS\")\n",
    "        print(\"CONGRATULATIONS!!\")\n",
    "        print(\"\\n\",\"\\n\",\"yash: CONGRATULATIONS\",name,\"YOU HAVE MADE INDIA PROUD!!\")\n",
    "    elif planet==7: #uranus\n",
    "        print(\"yash: finally\",roc_name,\"has successfully reached uranus! after travelling over 2.6 billion km for 12 years!\")\n",
    "        tm.sleep(1)\n",
    "        mission_date = datetime.strptime(final_date,\"%d/%m/%Y\")\n",
    "        print(\"yash: It's\",mission_date + relativedelta(years=12))\n",
    "        type_effect(\"Few days later.....\")\n",
    "        tm.sleep(3)\n",
    "        print(\"yash: after a few days of observation with the help of our probe, this is what we can conclude\")\n",
    "        print(\"===== MISSION REPORT =====\")\n",
    "        print(\"No evidence of life was detected.\")\n",
    "        print(\"Atmospheric resources may be useful for future robotic missions.\")\n",
    "        print(\"Human settlement is currently impractical.\")\n",
    "        print(\"THIS MISSION IS HEREBY CONSIDERED A SUCCESS\")\n",
    "        print(\"CONGRATULATIONS!!\")\n",
    "        print(\"\\n\",\"\\n\",\"yash: CONGRATULATIONS\",name,\"YOU HAVE MADE INDIA PROUD!!\")\n",
    "    elif planet==8: #neptune\n",
    "        print(\"yash: finally\",roc_name,\"has successfully reached neptune! after travelling over 4.3 billion km for 15 years!\")\n",
    "        tm.sleep(1)\n",
    "        mission_date = datetime.strptime(final_date,\"%d/%m/%Y\")\n",
    "        print(\"yash: It's\",mission_date + relativedelta(years=15))\n",
    "        type_effect(\"Few days later.....\")\n",
    "        tm.sleep(3)\n",
    "        print(\"yash: after a few days of observation with the help of our probe, this is what we can conclude\")\n",
    "        print(\"===== MISSION REPORT =====\")\n",
    "        print(\"Valuable atmospheric data was collected.\")\n",
    "        print(\"Extreme weather conditions make habitation impossible.\")\n",
    "        print(\"Further exploration should focus on Neptune's moons.\")\n",
    "        print(\"THIS MISSION IS HEREBY CONSIDERED A SUCCESS\")\n",
    "        print(\"CONGRATULATIONS!!\")\n",
    "        print(\"\\n\",\"\\n\",\"yash: CONGRATULATIONS\",name,\"YOU HAVE MADE INDIA PROUD!!\")\n",
    "    \n",
    "    "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
